# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd3f29a69f1a020eebbcbcee5d31199ae926b563cd7a7410cc836a557ff95dbd79306991bc7a175a0b2907a168c5321680a98d57bbfe9b6cdf25b257a725d57

test:
  secret_key_base: 08f2e89313fbabaa5b4c2068a271b2afc4e2769b7c1cef06a8f2a489f24aaeae2ef3de315151efff3cd117d8239d35bfeff81c47216dc47c1e88433f677f46bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
